### ISSUE TITLE
feat: allow pre-release versions

### ISSUE THREAD

**Issue by arsham** [lzambarda/vergo#1]
Thanks for the amazing library. 

I have a request for parsing strings like `v0.1.2-rc1`. Currently the patch part is assumed to be a number, but the mentioned form is also a valid form.

I would recommend bumping a release candidate of `v0.1.2-rc1` to become `v0.1.2`.

**Comment by lzambarda** [comment]
Excellent point! I was thinking about this.
Not sure about the bumping behaviour, what if one wants to bump from `v0.1.2-rc1` to `v0.1.2-rc2` ?

**Comment by arsham** [comment]
I think bumping with `BumpPatch` can advance `v0.1.2-rc1` to `v0.1.3` as usual, and a new bump constant can advance `v0.1.2` to `v0.1.2-rc1`, and `v0.1.2-rc1` to `v0.1.2-rc2`.

Now there is a question of how to manage `v0.1.2-alpha`, `v0.1.2-beta` and so on, that can make this process a bit messy.

**Comment by lzambarda** [comment]
Also vergo was unable to parse `v1.22.6-eks-7d68063`
